spring:
  application:
    name: remote-project-hub

  profiles:
    default: dev

  jackson:
    time-zone: UTC

server:
  port: ${PORT:8080}

# Tip: override at runtime:
# PORT=8081 ./gradlew bootRun


---

#logging:
#  level:
  # Uncomment if you want to debug security / SQL during dev
  # org.springframework.security: DEBUG
  # org.hibernate.SQL: DEBUG

