spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/remote_project_hub}
    username: ${DB_USERNAME:remote_hub_user}
    password: ${DB_PASSWORD:remote_hub_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # don't auto-change schema in prod
    properties:
      hibernate:
        format_sql: false # logs cleaner in prod
    show-sql: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO

security:
  jwt:
    secret: ${JWT_SECRET}
    validity-ms: ${JWT_VALIDITY_MS:86400000}
  refresh-token:
    validity-ms: ${REFRESH_TOKEN_VALIDITY_MS:1209600000}
